[Feature] Allow NULL values in timestamp_array and secondary_order_array in CELONIS_MERGE_SORTED_ARRAYS (#1426)
## Why I'm doing:
Recently ingestion removed timestamp and sorting from pk columns of
event tables. And we started to see the below SQL exception
```
java.sql.SQLException: SQL Exception [(conn=8082) If provided, secondary_order_array should not have NULL elements.: BE:17011] in [/* isWarmup = false */ set query_timeout = 600; set query_mem_limit=150000000000; set pipeline_dop=16; set pipeline_sink_dop=16; set partial_update_mode = "column"; set enable_profile=false;
```
This is because there are NULL values in secondary_order_array when
using CELONIS_MERGE_SORTED_ARRAYS.

## What I'm doing:

This PR changes CELONIS_MERGE_SORTED_ARRAYS to allow NULL values in
timestamp_array and secondary_order_array.

The new implementation is consistent with Saola's implementation which
puts NULL first during ordering (applies to both timestamp and sorting).

1. test when handling null when comparing timestamp:
[https://github.com/celonis/cpm-query-engine/blob/c12154cf8d34e345abaeb5174e149b79b[…]ive/cpm-accelerator/test/src/common/event_table_sorter_test.cpp](https://github.com/celonis/cpm-query-engine/blob/c12154cf8d34e345abaeb5174e149b79b2c0e942/query-engine/src/main/native/cpm-accelerator/test/src/common/event_table_sorter_test.cpp#L76)

2. test when handling null when comparing sorting:
[https://github.com/celonis/cpm-query-engine/blob/c12154cf8d34e345abaeb5174e149b79b[…]ive/cpm-accelerator/test/src/common/event_table_sorter_test.cpp](https://github.com/celonis/cpm-query-engine/blob/c12154cf8d34e345abaeb5174e149b79b2c0e942/query-engine/src/main/native/cpm-accelerator/test/src/common/event_table_sorter_test.cpp#L129)

Will change CELONIS_PEEK_MERGED_SORTED_ARRAYS in a different PR.

Tested locally.

```
SELECT CELONIS_MERGE_SORTED_ARRAYS(T.input, T.timestamp, T.size, T.priority, T.secondary_order, 1) sorted_array FROM (SELECT [110, 120, 215, 225, 310, 315, 320] AS input, [CAST('2023-01-01 00:00:20' AS DATETIME), CAST('2023-01-01 00:00:20' AS DATETIME), NULL, CAST('2023-01-01 00:00:25' AS DATETIME), CAST('2023-01-01 00:00:10' AS DATETIME), CAST('2023-01-01 00:00:15' AS DATETIME), CAST('2023-01-01 00:00:20' AS DATETIME)] AS timestamp, [2, 2, 3] AS size, [1, 1, 1, 1, 1, 1, 1] AS priority, ["apple", "apple", "cat", "cat", "bus", "bus", "bus"] AS secondary_order) AS T;
```
```
+--------------+
| sorted_array |
+--------------+
| [215]        |
+--------------+
```

```
SELECT CELONIS_MERGE_SORTED_ARRAYS(T.input, T.timestamp, T.size, T.priority, T.secondary_order, 1) sorted_array FROM (SELECT [110, 120, 215, 225, 310, 315, 320] AS input, [CAST('2023-01-01 00:00:20' AS DATETIME), CAST('2023-01-01 00:00:20' AS DATETIME), CAST('2023-01-01 00:00:20' AS DATETIME), CAST('2023-01-01 00:00:20' AS DATETIME), CAST('2023-01-01 00:00:20' AS DATETIME), CAST('2023-01-01 00:00:20' AS DATETIME), CAST('2023-01-01 00:00:20' AS DATETIME)] AS timestamp, [2, 2, 3] AS size, [1, 1, 1, 1, 1, 1, 1] AS priority, ["apple", "apple", "cat", "cat", NULL, "bus", "bus"] AS secondary_order) AS T;
```
```
+--------------+
| sorted_array |
+--------------+
| [310]        |
+--------------+
```

## What type of PR is this:

- [ ] BugFix
- [x] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

Does this PR entail a change in behavior?

- [x] Yes, this PR will result in a change in behavior.
- [ ] No, this PR will not result in a change in behavior.

If yes, please specify the type of change:

- [ ] Interface/UI changes: syntax, type conversion, expression
evaluation, display information
- [ ] Parameter changes: default values, similar parameters but with
different default values
- [ ] Policy changes: use new policy to replace old one, functionality
automatically enabled
- [ ] Feature removed
- [ ] Miscellaneous: upgrade & downgrade compatibility, etc.

## Checklist:

- [x] I have added test cases for my bug fix or my new feature
- [ ] This pr needs user documentation (for new or modified features or
behaviors)
  - [ ] I have added documentation for my new feature or new function
- [ ] This is a backport pr

## Bugfix cherry-pick branch check:
- [ ] I have checked the version labels which the pr will be
auto-backported to the target branch
  - [ ] 3.3
  - [ ] 3.2
  - [ ] 3.1
  - [ ] 3.0
  - [ ] 2.5