[Refactor] Transplant Celonis commits from branch-2.4-ubuntu to branch-2.5.0-5fad90c8-celo (#26)
Transplant celonis commits from `branch-2.4-ubuntu` to
`branch-2.5.0-5fad90c8-celo`

***Notes***:
- the first two commits in branch-2.4-ubuntu are excluded
- the change for allowing longer name are excluded because upstream
  already have it.

![image](https://user-images.githubusercontent.com/5108773/201835958-cc3448e8-cb05-49ef-97e6-6b9802501565.png)

```
[ 98%] Built target Exec
[ 99%] Building CXX object src/bench/CMakeFiles/chunks_sorter_bench.dir/chunks_sorter_bench.cpp.o
[ 99%] Building CXX object src/bench/CMakeFiles/runtime_filter_bench.dir/runtime_filter_bench.cpp.o
[ 99%] Building CXX object src/service/CMakeFiles/starrocks_be.dir/starrocks_main.cpp.o
[ 99%] Linking CXX executable root/devserver/celostar-starrocks/be/src/bench/runtime_filter_bench
[ 99%] Linking CXX executable root/devserver/celostar-starrocks/be/src/bench/chunks_sorter_bench
[100%] Linking CXX executable ../../../output/lib/starrocks_be
[100%] Built target chunks_sorter_bench
[100%] Built target runtime_filter_bench
[100%] Built target starrocks_be

real    17m52.868s
user    230m31.080s
sys     10m30.533s
... ...
[INFO] starrocks-java-extensions 1.0-SNAPSHOT ............. SUCCESS [  0.893 s]
[INFO] jdbc-bridge 1.0-SNAPSHOT ........................... SUCCESS [  1.761 s]
[INFO] java-utils 1.0.0 ................................... SUCCESS [  0.156 s]
[INFO] udf-extensions 1.0-SNAPSHOT ........................ SUCCESS [  0.610 s]
[INFO] jni-connector 1.0.0 ................................ SUCCESS [  0.131 s]
[INFO] hudi-reader 1.0-SNAPSHOT ........................... SUCCESS [ 10.951 s]
[INFO] udf-examples 1.0-SNAPSHOT .......................... SUCCESS [  0.062 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  14.622 s
[INFO] Finished at: 2022-11-15T06:03:01Z
[INFO] ------------------------------------------------------------------------
***************************************
Successfully build StarRocks
```
```
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] fe-common 1.0.0 .................................... SUCCESS [  1.334 s]
[INFO] spark-dpp 1.0.0 .................................... SUCCESS [  3.691 s]
[INFO] fe-core 3.4.0 ...................................... SUCCESS [ 32.426 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  37.521 s
[INFO] Finished at: 2022-11-15T06:08:07Z
[INFO] ------------------------------------------------------------------------
***************************************
Successfully build StarRocks
***************************************
```
```
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  3.541 s
[INFO] Finished at: 2022-11-15T06:08:50Z
[INFO] ------------------------------------------------------------------------
Install broker...
--2022-11-15 06:08:50--  http://cdn-thirdparty.starrocks.com/broker_thirdparty_jars.tar.gz
Resolving cdn-thirdparty.starrocks.com (cdn-thirdparty.starrocks.com)... 79.133.176.231, 79.133.176.230, 79.133.176.228, ...
Connecting to cdn-thirdparty.starrocks.com (cdn-thirdparty.starrocks.com)|79.133.176.231|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 15527686 (15M) [application/gzip]
Saving to: 'broker_thirdparty_jars.tar.gz'

100%[========================================================================================================>] 15,527,686  1.69MB/s   in 9.4s

2022-11-15 06:09:06 (1.57 MB/s) - 'broker_thirdparty_jars.tar.gz' saved [15527686/15527686]
```
```
[ 96%] Building CXX object test/CMakeFiles/starrocks_test.dir/service/lake_service_test.cpp.o
[ 96%] Building CXX object test/CMakeFiles/starrocks_test.dir/column/avx_numeric_column_test.cpp.o
[ 96%] Linking CXX executable starrocks_test
[100%] Built target starrocks_test

real    13m9.774s
user    47m23.966s
sys     3m31.786s
Finished
```
```
java.lang.Exception: open sink failed, backend:10001 txn:9700 index:10059 has intolerable failure: Too many versions. tablet_id: 10060, version_count: 1000, limit: 1000 [10001, 10002] numReplica:3 |
        at com.starrocks.pseudocluster.PseudoBackend.runSink(PseudoBackend.java:1123)
        at com.starrocks.pseudocluster.PseudoBackend.execBatchPlanFragment(PseudoBackend.java:1067)
        at com.starrocks.pseudocluster.PseudoBackend.execBatchPlanFragmentsWithReport(PseudoBackend.java:1094)
        at com.starrocks.pseudocluster.PseudoBackend.access$1100(PseudoBackend.java:130)
        at com.starrocks.pseudocluster.PseudoBackend$PseudoPBackendService.lambda$execBatchPlanFragmentsAsync$4(PseudoBackend.java:876)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:750)
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 19,542.544 s <<< FAILURE! - in com.starrocks.pseudocluster.DecommissionTest
[ERROR] testDecommission  Time elapsed: 19,536.993 s  <<< ERROR!
java.sql.SQLSyntaxErrorException: open sink failed, backend:10001 txn:9700 index:10059 has intolerable failure: Too many versions. tablet_id: 10060, version_count: 1000, limit: 1000 [10001, 10002] numReplica:3 |
        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:120)
        at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
        at com.mysql.cj.jdbc.StatementImpl.executeInternal(StatementImpl.java:763)
        at com.mysql.cj.jdbc.StatementImpl.execute(StatementImpl.java:648)
        at org.apache.commons.dbcp2.DelegatingStatement.execute(DelegatingStatement.java:193)
        at org.apache.commons.dbcp2.DelegatingStatement.execute(DelegatingStatement.java:193)
        at com.starrocks.pseudocluster.PseudoCluster.runSingleSql(PseudoCluster.java:255)
        at com.starrocks.pseudocluster.PseudoCluster.runSql(PseudoCluster.java:282)
        at com.starrocks.pseudocluster.PseudoCluster.runSql(PseudoCluster.java:290)
        at com.starrocks.pseudocluster.DecommissionTest.testDecommission(DecommissionTest.java:61)

[INFO]
[INFO] Results:
[INFO]
[ERROR] Failures:
[ERROR]   CreateMaterializedViewTest.createViewBadName:1961
[ERROR] Errors:
[ERROR]   DecommissionTest.testDecommission:61 ? SQLSyntaxError open sink failed, backen...
[INFO]
[ERROR] Tests run: 4405, Failures: 1, Errors: 1, Skipped: 5
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] starrocks-fe 3.4.0 ................................. SUCCESS [  0.001 s]
[INFO] fe-common 1.0.0 .................................... SUCCESS [  1.829 s]
[INFO] spark-dpp 1.0.0 .................................... SUCCESS [ 11.869 s]
[INFO] fe-core 3.4.0 ...................................... FAILURE [  05:39 h]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  05:39 h
[INFO] Finished at: 2022-11-15T12:50:07Z
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.22.2:test (default-test) on project fe-core: There are test failures.
[ERROR]
[ERROR] Please refer to /root/devserver/celostar-starrocks/fe/fe-core/target/surefire-reports for the individual test results.
[ERROR] Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <args> -rf :fe-core
```

[surefire-reports.zip](https://github.com/celonis/celostar-starrocks/files/10013909/surefire-reports.zip)
```
[WARNING] Tests run: 4400, Failures: 0, Errors: 0, Skipped: 5
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] starrocks-fe 3.4.0 ................................. SUCCESS [  0.002 s]
[INFO] fe-common 1.0.0 .................................... SUCCESS [  0.941 s]
[INFO] spark-dpp 1.0.0 .................................... SUCCESS [ 10.964 s]
[INFO] fe-core 3.4.0 ...................................... SUCCESS [16:50 min]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  17:02 min
[INFO] Finished at: 2022-11-15T15:40:55Z
[INFO] ------------------------------------------------------------------------
```

Co-authored-by: agubichev <andrey.gubichev@gmail.com>
Co-authored-by: Jiacheng Yang <103014487+jiacheng-celonis@users.noreply.github.com>
Co-authored-by: Rob Cauble <110474126+rcauble@users.noreply.github.com>
Co-authored-by: Vishnu Emmadi <101437218+idammev@users.noreply.github.com>